apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos
  labels:
    app: ms-productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-productos
  template:
    metadata:
      labels:
        app: ms-productos
    spec:
      containers:
        - name: ms-productos
          image: valencia123/ms-productos:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://ep-restless-bonus-atd7h7vc-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslMode=require&channel_binding=require"
            - name: SPRING_R2DBC_USERNAME
              value: "neondb_owner"
            - name: SPRING_R2DBC_PASSWORD
              value: "npg_JFIRq1Q8EWBs"
